package gao;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import java.util.List;

public interface ABDataBase {

	public Connection getConn();

	public Statement getST(Connection c);

	public PreparedStatement getPST(Connection c, String sql);

	public PreparedStatement getPST(Connection c, String sql,
			int autoGeneratedKey);

	public ResultSet executeQuery(Statement st, String sql);

	public int executeUpdate(Statement st, String sql);

	public void close(Connection c);

	public void close(Statement s);

	public void close(ResultSet rs);
	
	public User  find(String name);
	
	public int add(User user);
	
	public int delete(User user);
	
	public int update(User user);
	
	public void getAllCategory(List<Category> categorys);
	
	public int sepGetQuestions(List<Question> questions,int id,int pageSize,int pageNo);
	
	public int[] getAllCategoryId();
	
	public int add(Question q);
	
	public int delete(Question q);
	
	public int update(Question q);
	
	public List<Question> findQuestion(String cont) ;

	public String getAnswerByQuestionId(int questionId);
	
	public User obscureFind(String name);
}
