package gao;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

public class DataBase {
	public static Connection getConn() {
		Connection conn = null;
		try {
			Class.forName("com.mysql.jdbc.Driver");

			conn = DriverManager.getConnection("jdbc:mysql://localhost/bbs?"
					+ "user=root&password=guang");

		} catch (ClassNotFoundException e) {
			e.printStackTrace();
		} catch (SQLException e) {
			e.printStackTrace();
		}

		return conn;
	}

	public static Statement getST(Connection c) {
		Statement st = null;
		try {
			st = c.createStatement();
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return st;

	}
	public static PreparedStatement getPST(Connection c,String sql) {
		PreparedStatement pst = null;
		try {
			pst = c.prepareStatement(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return pst;

	}
	public static PreparedStatement getPST(Connection c,String sql,int autoGeneratedKey) {
		PreparedStatement pst = null;
		try {
			pst = c.prepareStatement(sql,autoGeneratedKey);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return pst;

	}

	public static ResultSet getQueryRS(Statement st, String sql) {
		ResultSet rs = null;
		try {
			rs = st.executeQuery(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return rs;

	}
	public static int executeUpdate(Statement st, String sql) {
		int affect = 0;
		try {
			affect = st.executeUpdate(sql);
		} catch (SQLException e) {
			e.printStackTrace();
		}
		return affect;

	}

	public static void close(Connection c) {
		try {
			if (c != null) {
				c.close();
				c = null;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public static void close(Statement s) {
		try {
			if (s != null) {
				s.close();
				s = null;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

	public static void close(ResultSet rs) {
		try {
			if (rs != null) {
				rs.close();
				rs = null;
			}
		} catch (SQLException e) {
			e.printStackTrace();
		}
	}

}
